# Generated by Django 2.1.2 on 2018-11-03 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiyat', models.FloatField(max_length=150)),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SatisKategorileri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kategoriName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urun_gorseli', models.CharField(max_length=400)),
                ('urun_ismi', models.CharField(max_length=400)),
                ('fiyat', models.FloatField(max_length=50)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SatisKategorileri')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='urun_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Urunler'),
        ),
    ]
