# Generated by Django 2.1.2 on 2018-11-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatisKategorileri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kategoriName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urun_gorseli', models.CharField(max_length=150)),
                ('urun_ismi', models.CharField(max_length=100)),
                ('fiyat', models.FloatField(max_length=50)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SatisKategorileri')),
            ],
        ),
    ]
