# Generated by Django 2.1.2 on 2018-11-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='urun_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Urunler'),
        ),
    ]
